export default {
    SET_JOKES_CATEGORIES: 'SET_JOKES_CATEGORIES',
    CHANGE_CATEGORY: 'CHANGE_CATEGORY',
    SHOW_JOKES: 'SHOW_JOKES',
    SHOW_FAVORITES: 'SHOW_FAVORITES',
    DISABLE_BUTTON: 'DISABLE_BUTTON'
}